"""tracking items, needs, and locations

Revision ID: 054ba47af208
Revises: 
Create Date: 2022-01-21 15:51:40.037343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054ba47af208'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=300), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_location',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('location_id', sa.Integer(), nullable=False),
        sa.Column('item_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
        sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_needed',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('item_id', sa.Integer(), nullable=False),
        sa.Column('needed_time', sa.DateTime(), nullable=False),
        sa.Column('cleared_time', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_needed')
    op.drop_table('item_location')
    op.drop_table('location')
    op.drop_table('items')
    # ### end Alembic commands ###
