"""adding color field to locations

Revision ID: 6cc23f8416f0
Revises: 054ba47af208
Create Date: 2022-07-21 14:57:22.221278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc23f8416f0'
down_revision = '054ba47af208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('color', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'color')
    # ### end Alembic commands ###
